namespace MismeAPI.Data.Entities.Enums
{
    public enum RewardCategoryEnum
    {
        POLL_ANSWERED, EAT_CREATED, EAT_BALANCED_CREATED, EAT_CREATED_STREAK, EAT_BALANCED_CREATED_STREAK, DISH_BUILT, NEW_REFERAL, CUT_POINT_REACHED, SOLO_QUESTION_ANSWERED
    }
}
