// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MismeAPI.Data;

namespace MismeAPI.Data.Migrations
{
    [DbContext(typeof(MismeContext))]
    [Migration("20201007181952_create_product_orders")]
    partial class create_product_orders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MismeAPI.Data.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TitleEN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TitleIT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("answer");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Version")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("app");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.CompoundDish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsAdminConverted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAdminReviewed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("compounddish");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Concept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Codename")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DescriptionIT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Instructions")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("InstructionsEN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("InstructionsIT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TitleEN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TitleIT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("concept");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.ContactUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAnswered")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<bool>("Read")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("contactus");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.CutPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("cutpoint");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("device");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double?>("Calcium")
                        .HasColumnType("double");

                    b.Property<double?>("Calories")
                        .HasColumnType("double");

                    b.Property<double?>("Carbohydrates")
                        .HasColumnType("double");

                    b.Property<double?>("Cholesterol")
                        .HasColumnType("double");

                    b.Property<string>("Code")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("Fat")
                        .HasColumnType("double");

                    b.Property<double?>("Fiber")
                        .HasColumnType("double");

                    b.Property<double?>("FolicAcid")
                        .HasColumnType("double");

                    b.Property<int>("HandCode")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ImageMimeType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double?>("Iron")
                        .HasColumnType("double");

                    b.Property<bool>("IsCaloric")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFruitAndVegetables")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsProteic")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("Magnesium")
                        .HasColumnType("double");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("MonoUnsaturatedFat")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NameEN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NameIT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double?>("NetWeight")
                        .HasColumnType("double");

                    b.Property<double?>("Phosphorus")
                        .HasColumnType("double");

                    b.Property<double?>("PolyUnsaturatedFat")
                        .HasColumnType("double");

                    b.Property<double?>("Potassium")
                        .HasColumnType("double");

                    b.Property<double?>("Proteins")
                        .HasColumnType("double");

                    b.Property<double?>("SaturatedFat")
                        .HasColumnType("double");

                    b.Property<double?>("Sodium")
                        .HasColumnType("double");

                    b.Property<double?>("VitaminA")
                        .HasColumnType("double");

                    b.Property<double?>("VitaminB12")
                        .HasColumnType("double");

                    b.Property<double?>("VitaminB1Thiamin")
                        .HasColumnType("double");

                    b.Property<double?>("VitaminB2Riboflavin")
                        .HasColumnType("double");

                    b.Property<double?>("VitaminB3Niacin")
                        .HasColumnType("double");

                    b.Property<double?>("VitaminB6")
                        .HasColumnType("double");

                    b.Property<double?>("VitaminB9Folate")
                        .HasColumnType("double");

                    b.Property<double?>("VitaminC")
                        .HasColumnType("double");

                    b.Property<double?>("VitaminD")
                        .HasColumnType("double");

                    b.Property<double?>("VitaminE")
                        .HasColumnType("double");

                    b.Property<double?>("VitaminK")
                        .HasColumnType("double");

                    b.Property<double?>("Volume")
                        .HasColumnType("double");

                    b.Property<double?>("Zinc")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("dish");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.DishCompoundDish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CompoundDishId")
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<double>("DishQty")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CompoundDishId");

                    b.HasIndex("DishId");

                    b.ToTable("dishcompounddish");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.DishTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TaggedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("TagId");

                    b.ToTable("dishtag");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Eat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EatType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EatUtcAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("ImcAtThatMoment")
                        .HasColumnType("double");

                    b.Property<bool>("IsBalanced")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsBalancedPlan")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("KCalAtThatMoment")
                        .HasColumnType("double");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PlanCreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("eat");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.EatCompoundDish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CompoundDishId")
                        .HasColumnType("int");

                    b.Property<int>("EatId")
                        .HasColumnType("int");

                    b.Property<double>("Qty")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CompoundDishId");

                    b.HasIndex("EatId");

                    b.ToTable("eatcompounddish");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.EatDish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("EatId")
                        .HasColumnType("int");

                    b.Property<double>("Qty")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("EatId");

                    b.ToTable("eatdish");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.EatSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EatId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EatId")
                        .IsUnique();

                    b.HasIndex("ScheduleId");

                    b.ToTable("eatschedule");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.FavoriteDish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("UserId");

                    b.ToTable("favoritedish");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.GeneralContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ContentEN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ContentIT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ContentType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("generalcontent");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.LackSelfControlDish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("Intensity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("UserId");

                    b.ToTable("lackselfcontroldishes");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExternalId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusInformation")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserEmail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserFullName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ConceptId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DescriptionIT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("HtmlContentEN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("HtmlContentIT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NameEN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NameIT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.ToTable("poll");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DescriptionEN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DescriptionIT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NameEN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NameIT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("product");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PollId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TitleEN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TitleIT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("question");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("BodyEN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("BodyIT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CodeName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CronExpression")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TitleEN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TitleIT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("reminder");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CodeName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ConceptName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Text")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TextEN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TextIT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("result");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.RewardAcumulate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("RewardCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RewardCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("rewardacumulate");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.RewardCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("MaxPointsAllowed")
                        .HasColumnType("int");

                    b.Property<int>("PointsToDecrement")
                        .HasColumnType("int");

                    b.Property<int>("PointsToIncrement")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("rewardcategory");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.RewardHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Data")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsPlus")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("RewardCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RewardCategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("rewardhistory");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("schedule");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("setting");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.SoloAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("SoloQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TitleEN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TitleIT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("SoloQuestionId");

                    b.ToTable("soloanswer");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.SoloQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AllowCustomAnswer")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TitleEN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TitleIT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("soloquestion");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Product")
                        .HasColumnType("int");

                    b.Property<int>("ValueCoins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("subscription");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("tag");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Tip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ContentEN")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ContentIT")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PollId")
                        .HasColumnType("int");

                    b.Property<int>("TipPosition")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("tip");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AvatarMimeType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("BreakFastKCalPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(20);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("CurrentImc")
                        .HasColumnType("double");

                    b.Property<double>("CurrentKcal")
                        .HasColumnType("double");

                    b.Property<int>("DinnerKCalPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(25);

                    b.Property<DateTime?>("DisabledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("FirtsHealthMeasured")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("LastLoggedIn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LunchKCalPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(35);

                    b.Property<bool>("MarkedForDeletion")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PaypalCustomerId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Snack1KCalPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<int>("Snack2KCalPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("TermsAndConditionsAccepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TimeZone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("TimeZoneOffset")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("VerificationCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("UserId");

                    b.ToTable("useranswer");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserConcept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ConceptId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.HasIndex("UserId");

                    b.ToTable("userconcept");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserReferral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("InvitedId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvitedId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("userreferral");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("JobConstant")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserTimeZone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("userschedule");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("SettingId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("SettingId");

                    b.HasIndex("UserId");

                    b.ToTable("usersetting");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserSoloAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AnswerCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AnswerValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Coins")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("QuestionCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("SoloAnswerId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SoloAnswerId");

                    b.HasIndex("UserId");

                    b.ToTable("usersoloanswer");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BalancedEatCurrentStreak")
                        .HasColumnType("int");

                    b.Property<int>("BalancedEatMaxStreak")
                        .HasColumnType("int");

                    b.Property<int>("Coins")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EatCurrentStreak")
                        .HasColumnType("int");

                    b.Property<int>("EatMaxStreak")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("TotalBalancedEatsPlanned")
                        .HasColumnType("int");

                    b.Property<int>("TotalNonBalancedEatsPlanned")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("userstatistics");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("ValidDays")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("usersubscription");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserSubscriptionSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("UserSubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("UserSubscriptionId")
                        .IsUnique();

                    b.ToTable("usersubscriptionschedule");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccessToken")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTimeOffset>("AccessTokenExpiresDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ClientName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClientType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClientVersion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DeviceBrand")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DeviceModel")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OS")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OSPlatform")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OSVersion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTimeOffset>("RefreshTokenExpiresDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("usertoken");
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Answer", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.CompoundDish", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.User", "CreatedBy")
                        .WithMany("CompoundDishs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.ContactUs", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Device", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.User", null)
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.DishCompoundDish", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.CompoundDish", "CompoundDish")
                        .WithMany("DishCompoundDishes")
                        .HasForeignKey("CompoundDishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MismeAPI.Data.Entities.Dish", "Dish")
                        .WithMany("DishCompoundDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.DishTag", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.Dish", "Dish")
                        .WithMany("DishTags")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MismeAPI.Data.Entities.Tag", "Tag")
                        .WithMany("DishTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Eat", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.User", "User")
                        .WithMany("Eats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.EatCompoundDish", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.CompoundDish", "CompoundDish")
                        .WithMany("EatCompoundDishes")
                        .HasForeignKey("CompoundDishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MismeAPI.Data.Entities.Eat", "Eat")
                        .WithMany("EatCompoundDishes")
                        .HasForeignKey("EatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.EatDish", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.Dish", "Dish")
                        .WithMany("EatDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MismeAPI.Data.Entities.Eat", "Eat")
                        .WithMany("EatDishes")
                        .HasForeignKey("EatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.EatSchedule", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.Eat", "Eat")
                        .WithOne("EatSchedule")
                        .HasForeignKey("MismeAPI.Data.Entities.EatSchedule", "EatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MismeAPI.Data.Entities.Schedule", "Schedule")
                        .WithMany("EatSchedules")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.FavoriteDish", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.Dish", "Dish")
                        .WithMany("FavoriteDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MismeAPI.Data.Entities.User", "User")
                        .WithMany("FavoriteDishes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.LackSelfControlDish", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.Dish", "Dish")
                        .WithMany("LackSelfControlDishes")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MismeAPI.Data.Entities.User", "User")
                        .WithMany("LackSelfControlDishes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Order", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MismeAPI.Data.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Poll", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.Concept", "Concept")
                        .WithMany("Polls")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Question", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.Poll", "Poll")
                        .WithMany("Questions")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.RewardAcumulate", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.RewardCategory", "RewardCategory")
                        .WithMany("RewardAcumulates")
                        .HasForeignKey("RewardCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MismeAPI.Data.Entities.User", "User")
                        .WithMany("RewardAcumulates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.RewardHistory", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.RewardCategory", "RewardCategory")
                        .WithMany("RewardHistories")
                        .HasForeignKey("RewardCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MismeAPI.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.SoloAnswer", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.SoloQuestion", "SoloQuestion")
                        .WithMany("SoloAnswers")
                        .HasForeignKey("SoloQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.Tip", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.Poll", "Poll")
                        .WithMany("Tips")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserAnswer", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.Answer", "Answer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MismeAPI.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserConcept", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.Concept", "Concept")
                        .WithMany("UserConcepts")
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MismeAPI.Data.Entities.User", "User")
                        .WithMany("UserConcepts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserReferral", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.User", "Invited")
                        .WithOne("Invitation")
                        .HasForeignKey("MismeAPI.Data.Entities.UserReferral", "InvitedId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MismeAPI.Data.Entities.User", "User")
                        .WithMany("Referrals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserSchedule", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.Schedule", "Schedule")
                        .WithMany("UserSchedules")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MismeAPI.Data.Entities.User", "User")
                        .WithMany("UserSchedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserSetting", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.Setting", "Setting")
                        .WithMany()
                        .HasForeignKey("SettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MismeAPI.Data.Entities.User", "User")
                        .WithMany("UserSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserSoloAnswer", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.SoloAnswer", "SoloAnswer")
                        .WithMany("UserSoloAnswers")
                        .HasForeignKey("SoloAnswerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MismeAPI.Data.Entities.User", "User")
                        .WithMany("UserSoloAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserStatistics", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.User", "User")
                        .WithOne("UserStatistics")
                        .HasForeignKey("MismeAPI.Data.Entities.UserStatistics", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserSubscription", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.Subscription", "Subscription")
                        .WithMany("Subscribers")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MismeAPI.Data.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserSubscriptionSchedule", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.Schedule", "Schedule")
                        .WithMany("UserSubscriptionSchedules")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MismeAPI.Data.Entities.UserSubscription", "UserSubscription")
                        .WithOne("UserSubscriptionSchedule")
                        .HasForeignKey("MismeAPI.Data.Entities.UserSubscriptionSchedule", "UserSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MismeAPI.Data.Entities.UserToken", b =>
                {
                    b.HasOne("MismeAPI.Data.Entities.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
