name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      API_PATH: ./MismeAPI/MismeAPI/MismeAPI.csproj 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore $API_PATH
    - name: Build
      run: dotnet build --no-restore $API_PATH
    - name: Test
      run: dotnet test --no-build --verbosity normal $API_PATH
